name: Android CI
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 1.18
      uses: actions/setup-java@v3
      with:
          distribution: temurin
          java-version: 18
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: assembleRelease
    - name: Build debug apk with Gradle
      run: cd project && bash ./gradlew clean assembleRelease && tree ./app/build/outputs/
    - uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: project/app/build/outputs/apk/debug/app-debug.apk
